apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "k6-cron.fullname" . }}
  namespace: {{ .Values.namespace | quote }}
  labels:
    {{- include "k6-cron.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.cronjob.schedule | quote }}
  concurrencyPolicy: {{ .Values.cronjob.concurrencyPolicy }}
  successfulJobsHistoryLimit: {{ .Values.cronjob.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.cronjob.failedJobsHistoryLimit }}
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        metadata:
          labels:
            {{- include "k6-cron.labels" . | nindent 12 }}
        spec:
          restartPolicy: Never
          containers:
            - name: k6
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              args:
                {{- toYaml .Values.k6.args | nindent 16 }}
              {{- if .Values.k6.env }}
              env:
                {{- toYaml .Values.k6.env | nindent 16 }}
              {{- end }}
              volumeMounts:
                - name: scripts
                  mountPath: /scripts
              resources:
                {{- toYaml .Values.resources | nindent 16 }}
          volumes:
            - name: scripts
              configMap:
                name: {{ include "k6-cron.fullname" . }}-scripts
